version: '3'

volumes:
  app:
  db:

networks:
  internal:
    external: false
  reverse-proxy:
    external:
      name: reverse-proxy

services:
  db:
    build: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - internal
  app:
    image: nextcloud:fpm
    depends_on:
      - db
    volumes:
      - app:/var/www/html
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - internal
  web:
    build: ./web
    depends_on:
      - app
    volumes:
      - app:/var/www/html:ro
    restart: unless-stopped
    networks:
      - internal
      - reverse-proxy
    labels:
      - traefik.enable=true
      - traefik.backend=nextcloud
      - traefik.frontend.rule=Host:nextcloud2.tensouth.net
      - traefik.docker.network=reverse-proxy
